In [14]:
import pandas as pd

#datafile = '/Users/Nayana/Documents/Notebooks/Recommender/ml-100k/u.data'
#data = pd.read_csv(datafile, sep="\t", header = None, usecols = [0,1,2],names = ['userid', 'itemid','rating'])

#Reading users file:
userFile = '/Users/Nayana/Desktop/Ramesha/Learnings/Python/ml-100k/u.user'
u_cols = ['user_id', 'age', 'sex', 'occupation', 'zip_code']
users = pd.read_csv(userFile, sep='|', names=u_cols, encoding='latin-1')

In [15]:
print(users.shape)
users.head()

(943, 5)


user_id  age sex  occupation zip_code
0        1   24   M  technician    85711
1        2   53   F       other    94043
2        3   23   M      writer    32067
3        4   24   M  technician    43537
4        5   33   F       other    15213

In [16]:
#Reading ratings file:
ratingsFile = '/Users/Nayana/Desktop/Ramesha/Learnings/Python/ml-100k/u.data'

r_cols = ['user_id', 'movie_id', 'rating', 'unix_timestamp']
ratings = pd.read_csv(ratingsFile, sep='\t', names=r_cols, encoding='latin-1')

In [17]:
print(ratings.shape)
ratings.head()

(100000, 4)


user_id  movie_id  rating  unix_timestamp
0      196       242       3       881250949
1      186       302       3       891717742
2       22       377       1       878887116
3      244        51       2       880606923
4      166       346       1       886397596

In [18]:
#Reading items file:
movieFile = '/Users/Nayana/Desktop/Ramesha/Learnings/Python/ml-100k/u.item'

i_cols = ['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
             'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 
              'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
items = pd.read_csv(movieFile, sep='|', names=i_cols, encoding='latin-1')

In [19]:
print(items.shape)
items.head()

(1682, 24)


movie id        movie title release date  video release date  \
0         1   Toy Story (1995)  01-Jan-1995                 NaN   
1         2   GoldenEye (1995)  01-Jan-1995                 NaN   
2         3  Four Rooms (1995)  01-Jan-1995                 NaN   
3         4  Get Shorty (1995)  01-Jan-1995                 NaN   
4         5     Copycat (1995)  01-Jan-1995                 NaN   

                                            IMDb URL  unknown  Action  \
0  http://us.imdb.com/M/title-exact?Toy%20Story%2...        0       0   
1  http://us.imdb.com/M/title-exact?GoldenEye%20(...        0       1   
2  http://us.imdb.com/M/title-exact?Four%20Rooms%...        0       0   
3  http://us.imdb.com/M/title-exact?Get%20Shorty%...        0       1   
4  http://us.imdb.com/M/title-exact?Copycat%20(1995)        0       0   

   Adventure  Animation  Children's   ...     Fantasy  Film-Noir  Horror  \
0          0          1           1   ...           0          0       0   
1          1          0           0   ...           0          0       0   
2          0          0           0   ...           0          0       0   
3          0          0           0   ...           0          0       0   
4          0          0           0   ...           0          0       0   

   Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western  
0        0        0        0       0         0    0        0  
1        0        0        0       0         1    0        0  
2        0        0        0       0         1    0        0  
3        0        0        0       0         0    0        0  
4        0        0        0       0         1    0        0  

[5 rows x 24 columns]

In [5]:
import pandas as pd
from numpy import *

num_movies =10
num_users = 5
ratings = random.randint(6, size = (num_movies,num_users))
print(ratings)


[[2 0 1 4 2]
 [1 1 3 5 4]
 [0 2 5 4 1]
 [1 3 5 0 2]
 [2 3 1 4 2]
 [4 4 2 3 1]
 [3 5 4 1 0]
 [3 3 4 4 4]
 [3 5 0 3 0]
 [3 1 4 5 4]]


In [8]:
#randon is normal distribution of random number
movie_features = random.randn(6,3)
print(movie_features)

[[ 1.34277398  0.89254352 -0.19162466]
 [-0.0472801   0.59157508  0.34143359]
 [-0.5454964   1.59501171  0.67334054]
 [ 0.89779419  0.6181237  -1.1670344 ]
 [ 0.96018248 -0.4639283  -0.71274131]
 [ 0.04877152 -0.38953212 -0.14679353]]
